// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvtFqKZENYQKlWm5TghjXUkKPwq-9Slo0',
    appId: '1:568643965020:web:b1fbe122b1014003cdd699',
    messagingSenderId: '568643965020',
    projectId: 'mini-project-8358b',
    authDomain: 'mini-project-8358b.firebaseapp.com',
    storageBucket: 'mini-project-8358b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT93jRckSTZt7L_XuuFxsLQNsjAS8b_vM',
    appId: '1:568643965020:android:34ca68157d955b15cdd699',
    messagingSenderId: '568643965020',
    projectId: 'mini-project-8358b',
    storageBucket: 'mini-project-8358b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvlWNiJqpPpfjUK3_nD7B9tUKLjsFKmlw',
    appId: '1:568643965020:ios:07067b98fadcbefecdd699',
    messagingSenderId: '568643965020',
    projectId: 'mini-project-8358b',
    storageBucket: 'mini-project-8358b.appspot.com',
    iosClientId: '568643965020-ubk78irnhqcjdamccspr956k8gebfesc.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvlWNiJqpPpfjUK3_nD7B9tUKLjsFKmlw',
    appId: '1:568643965020:ios:07067b98fadcbefecdd699',
    messagingSenderId: '568643965020',
    projectId: 'mini-project-8358b',
    storageBucket: 'mini-project-8358b.appspot.com',
    iosClientId: '568643965020-ubk78irnhqcjdamccspr956k8gebfesc.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );
}
